# Generated by Django 4.2.9 on 2025-11-25 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth2_provider', '0013_alter_application_authorization_grant_type_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGrantOIDC',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_code', models.CharField(max_length=100, unique=True)),
                ('user_code', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=64, null=True)),
                ('interval', models.IntegerField(default=5)),
                ('expires', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('authorized', 'Authorized'), ('authorization-pending', 'Authorization pending'), ('expired', 'Expired'), ('denied', 'Denied')], default='authorization-pending', max_length=64)),
                ('client_id', models.CharField(db_index=True, max_length=100)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('auth_time', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'swappable': 'OAUTH2_PROVIDER_DEVICE_GRANT_MODEL',
            },
        ),
        migrations.AddConstraint(
            model_name='devicegrantoidc',
            constraint=models.UniqueConstraint(fields=('device_code',), name='oauth2_provider_devicegrantoidc_unique_device_code'),
        ),
    ]
