# Generated by Django 4.2.9 on 2025-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0014_devicegrantoidc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegrantoidc',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
